# Generated by Django 2.2.16 on 2020-12-12 20:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0028_auto_20201212_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 23, 39, 42, 937242), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 23, 39, 42, 938242), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('them', models.CharField(choices=[('1', 'Создать файл'), ('2', 'Найти файл'), ('3', 'Поделиться файлом')], max_length=1)),
                ('text', models.TextField(verbose_name='Подробнее о файле')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 12, 23, 39, 42, 938242), verbose_name='Дата')),
                ('status', models.CharField(choices=[('1', 'В ожидании'), ('2', 'Выполнено'), ('3', 'Отказ')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'Zakaz',
                'ordering': ['-date'],
            },
        ),
    ]
