# Generated by Django 2.2.16 on 2020-12-12 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20201212_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 13, 0, 19, 45, 481414), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 13, 0, 19, 45, 482413), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 12, 13, 0, 19, 45, 482413), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='status',
            field=models.CharField(choices=[('1', 'В ожидании'), ('2', 'Выполнено'), ('3', 'Отказ')], default='1', max_length=1),
        ),
    ]
